# 定义失败状态码的偏移量
STATUS_SEC_FAILURE_OFFSET: int = 1000
STATUS_THIRD_FAILURE_OFFSET: int = 10


class CodeStatus:
    class BasicCommunication:
        class FaBBasicCommunication:
            STATUS_FIR = 10000
            STATUS_SEC = 000

            def success_status(self, code_suffix):
                return self.STATUS_FIR + self.STATUS_SEC + code_suffix, f'获取{"全部界面资源" if code_suffix == 0 else ("界面主题资源" if code_suffix == 1 else "界面配色参数")}成功'

            def failure_status(self, success_status):
                return success_status[0] + STATUS_THIRD_FAILURE_OFFSET, f'{success_status[1].replace("成功", "失败")}'

            ALL_VIEW_ASSETS_SUCCESS = success_status(0)
            ALL_VIEW_THEME_ASSETS_SUCCESS = success_status(1)
            ALL_VIEW_COLOR_SUCCESS = success_status(2)

            ALL_VIEW_ASSETS_FAILURE = failure_status(ALL_VIEW_ASSETS_SUCCESS)
            ALL_VIEW_THEME_ASSETS_FAILURE = failure_status(ALL_VIEW_THEME_ASSETS_SUCCESS)
            ALL_VIEW_COLOR_FAILURE = failure_status(ALL_VIEW_COLOR_SUCCESS)

        class UserArchive:
            STATUS_SEC = 100
            USER_ARCHIVE_SUCCESS = 0 + STATUS_FIR + STATUS_SEC, '用户信息功能正常'
            USER_ARCHIVE_REGISTER_SUCCESS = 1 + STATUS_FIR + STATUS_SEC, '用户信息注册成功'
            USER_ARCHIVE_LOGIN_SUCCESS = 2 + STATUS_FIR + STATUS_SEC, '用户信息登录成功'
            USER_ARCHIVE_REVISE_SUCCESS = 3 + STATUS_FIR + STATUS_SEC, '用户信息修改成功'
            USER_ARCHIVE_FREEZE_SUCCESS = 4 + STATUS_FIR + STATUS_SEC, '用户信息冻结成功'
            USER_ARCHIVE_REFREEZE_SUCCESS = 5 + STATUS_FIR + STATUS_SEC, '用户信息解冻成功'
            USER_ARCHIVE_DELETE_SUCCESS = 6 + STATUS_FIR + STATUS_SEC, '用户信息注销成功'
            USER_ARCHIVE_NOT_FOUND = 7 + STATUS_FIR + STATUS_SEC, '用户信息无法找到'
            USER_ARCHIVE_FOUNDED = 8 + STATUS_FIR + STATUS_SEC, '用户信息成功找到'

            USER_ARCHIVE_FAILURE = USER_ARCHIVE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户信息功能异常'
            USER_ARCHIVE_REGISTER_FAILURE = USER_ARCHIVE_REGISTER_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户信息注册失败'
            USER_ARCHIVE_LOGIN_FAILURE = USER_ARCHIVE_LOGIN_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户信息登录失败'
            USER_ARCHIVE_REVISE_FAILURE = USER_ARCHIVE_REVISE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户信息修改失败'
            USER_ARCHIVE_FREEZE_FAILURE = USER_ARCHIVE_FREEZE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户信息冻结失败'
            USER_ARCHIVE_REFREEZE_FAILURE = USER_ARCHIVE_REFREEZE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户信息解冻失败'
            USER_ARCHIVE_DELETE_FAILURE = USER_ARCHIVE_DELETE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户信息注销失败'
            USER_ARCHIVE_NOT_FOUND_FAILURE = USER_ARCHIVE_NOT_FOUND[0] + STATUS_THIRD_FAILURE_OFFSET, '用户信息无法找到失败'
            USER_ARCHIVE_FOUNDED_FAILURE = USER_ARCHIVE_FOUNDED[0] + STATUS_THIRD_FAILURE_OFFSET, '用户信息失败找到'

            USER_COUPON_SUCCESS_GET = 20 + STATUS_FIR + STATUS_SEC, '用户优惠券获取成功'
            USER_COUPON_SUCCESS_DELETE = 21 + STATUS_FIR + STATUS_SEC, '用户优惠券删除成功'
            USER_CART_SUCCESS_ADD = 22 + STATUS_FIR + STATUS_SEC, '用户购物车添加成功'
            USER_CART_SUCCESS_DELETE = 23 + STATUS_FIR + STATUS_SEC, '用户购物车删除成功'
            USER_ORDER_CREATE_SUCCESS = 24 + STATUS_FIR + STATUS_SEC, '用户订单创建成功'
            USER_ORDER_DELETE_SUCCESS = 25 + STATUS_FIR + STATUS_SEC, '用户订单删除成功'
            USER_PAYMENT_SUCCESS = 26 + STATUS_FIR + STATUS_SEC, '用户付款成功'
            USER_ORDER_SEARCH_SUCCESS_BUT_NO_ITEM = 27 + STATUS_FIR + STATUS_SEC, '用户订单获取成功，但没有订单'
            USER_ORDER_SEARCH_SUCCESS_HAVE_ITEM = 28 + STATUS_FIR + STATUS_SEC, '用户订单获取成功，有订单'

            USER_COUPON_FAILURE_GET = USER_COUPON_SUCCESS_GET[0] + STATUS_THIRD_FAILURE_OFFSET, '用户优惠券获取失败'
            USER_COUPON_FAILURE_DELETE = USER_COUPON_SUCCESS_DELETE[0] + STATUS_THIRD_FAILURE_OFFSET, '用户优惠券删除失败'
            USER_CART_FAILURE_ADD = USER_CART_SUCCESS_ADD[0] + STATUS_THIRD_FAILURE_OFFSET, '用户购物车添加失败'
            USER_CART_FAILURE_DELETE = USER_CART_SUCCESS_DELETE[0] + STATUS_THIRD_FAILURE_OFFSET, '用户购物车删除失败'
            USER_ORDER_CREATE_FAILURE = USER_ORDER_CREATE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户订单创建失败'
            USER_ORDER_DELETE_FAILURE = USER_ORDER_DELETE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户订单删除失败'
            USER_PAYMENT_FAILURE = USER_PAYMENT_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户付款失败'
            USER_ORDER_SEARCH_FAILURE_BUT_NO_ITEM = USER_ORDER_SEARCH_SUCCESS_BUT_NO_ITEM[
                                                        0] + STATUS_THIRD_FAILURE_OFFSET, '用户订单获取失败，但没有订单'
            USER_ORDER_SEARCH_FAILURE_HAVE_ITEM = USER_ORDER_SEARCH_SUCCESS_HAVE_ITEM[
                                                      0] + STATUS_THIRD_FAILURE_OFFSET, '用户订单获取失败，有订单'

            USER_APPLICATION_REFUND_SUCCESS = 40 + STATUS_FIR + STATUS_SEC, '用户申请退款成功'
            USER_REVOKE_REFUND_SUCCESS = 41 + STATUS_FIR + STATUS_SEC, '用户撤销退款成功'
            USER_APPLICATION_EXCHANGE_COMMODITY_SUCCESS = 42 + STATUS_FIR + STATUS_SEC, '用户申请换货成功'
            USER_REVOKE_EXCHANGE_COMMODITY_SUCCESS = 43 + STATUS_FIR + STATUS_SEC, '用户撤销换货成功'
            USER_APPLICATION_SERVICE_SUCCESS = 44 + STATUS_FIR + STATUS_SEC, '用户申请售后介入成功'
            USER_REVOKE_SERVICE_SUCCESS = 45 + STATUS_FIR + STATUS_SEC, '用户撤销售后介入成功'
            USER_CONFIRM_RECEIPT_SUCCESS = 46 + STATUS_FIR + STATUS_SEC, '用户确认收货成功'

            USER_APPLICATION_REFUND_FAILURE = USER_APPLICATION_REFUND_SUCCESS[
                                                  0] + STATUS_THIRD_FAILURE_OFFSET, '用户申请退款失败'
            USER_REVOKE_REFUND_FAILURE = USER_REVOKE_REFUND_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户撤销退款失败'
            USER_APPLICATION_EXCHANGE_COMMODITY_FAILURE = USER_APPLICATION_EXCHANGE_COMMODITY_SUCCESS[
                                                              0] + STATUS_THIRD_FAILURE_OFFSET, '用户申请换货失败'
            USER_REVOKE_EXCHANGE_COMMODITY_FAILURE = USER_REVOKE_EXCHANGE_COMMODITY_SUCCESS[
                                                         0] + STATUS_THIRD_FAILURE_OFFSET, '用户撤销换货失败'
            USER_APPLICATION_SERVICE_FAILURE = USER_APPLICATION_SERVICE_SUCCESS[
                                                   0] + STATUS_THIRD_FAILURE_OFFSET, '用户申请售后介入失败'
            USER_REVOKE_SERVICE_FAILURE = USER_REVOKE_SERVICE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户撤销售后介入失败'
            USER_CONFIRM_RECEIPT_FAILURE = USER_CONFIRM_RECEIPT_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '用户确认收货失败'

        class Commodity:
            STATUS_SEC = 200
            COM_DETAILS_GET_SUCCESS = 0 + STATUS_FIR + STATUS_SEC, '获取商品详情信息成功'
            COM_LIST_VIEW_DATA_GET_SUCCESS = 1 + STATUS_FIR + STATUS_SEC, '获取商品列表界面数据成功'
            COM_3DMODEL_GET_SUCCESS = 2 + STATUS_FIR + STATUS_SEC, '获取商品3D模型成功'

            COM_DETAILS_GET_FAILURE = COM_DETAILS_GET_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '获取商品详情信息失败'
            COM_LIST_VIEW_DATA_GET_FAILURE = COM_LIST_VIEW_DATA_GET_SUCCESS[
                                                 0] + STATUS_THIRD_FAILURE_OFFSET, '获取商品列表界面数据失败'
            COM_3DMODEL_GET_FAILURE = COM_3DMODEL_GET_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '获取商品3D模型失败'

    class AdminCommunication:
        STATUS_FIR = 20000

        class Commodity:
            STATUS_SEC = 000
            COM_ADD_SUCCESS = 0 + STATUS_FIR + STATUS_SEC, '商品添加成功'
            COM_CHANGE_SUCCESS = 1 + STATUS_FIR + STATUS_SEC, '商品修改成功'
            COM_DELETE_SUCCESS = 2 + STATUS_FIR + STATUS_SEC, '商品删除成功'

            COM_ADD_FAILURE = COM_ADD_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '商品添加失败'
            COM_CHANGE_FAILURE = COM_CHANGE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '商品修改失败'
            COM_DELETE_FAILURE = COM_DELETE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '商品删除失败'

    class TokenCommunication:
        STATUS_FIR = 30000

        class TokenIssuance:
            STATUS_SEC = 000
            TOKEN_ISSUE_SUCCESS = 0 + STATUS_FIR + STATUS_SEC, '令牌签发成功'
            TOKEN_PROVING_SUCCESS = 1 + STATUS_FIR + STATUS_SEC, '令牌验证成功'
            TOKEN_AUTHENTICATION_SUCCESS = 2 + STATUS_FIR + STATUS_SEC, '令牌鉴权成功'
            TOKEN_EXCHANGE_SUCCESS = 3 + STATUS_FIR + STATUS_SEC, '令牌兑换成功'
            TOKEN_ISSUE_FOREVER_SUCCESS = 4 + STATUS_FIR + STATUS_SEC, '令牌终身有效签发成功'

            TOKEN_ISSUE_FAILURE = TOKEN_ISSUE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '令牌签发失败'
            TOKEN_PROVING_FAILURE = TOKEN_PROVING_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '令牌验证失败'
            TOKEN_AUTHENTICATION_FAILURE = TOKEN_AUTHENTICATION_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '令牌鉴权失败'
            TOKEN_EXCHANGE_FAILURE = TOKEN_EXCHANGE_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '令牌兑换失败'
            TOKEN_ISSUE_FOREVER_FAILURE = TOKEN_ISSUE_FOREVER_SUCCESS[0] + STATUS_THIRD_FAILURE_OFFSET, '令牌终身有效签发失败'

        class TokenDetailsStatus:
            STATUS_SEC = 100
            TOKEN_EFFECTIVE = 0 + STATUS_FIR + STATUS_SEC, '令牌合法有效！'
            TOKEN_VALUE_ERROR = 1 + STATUS_FIR + STATUS_SEC, '你看看你Token传的什么玩意？'
            TOKEN_EXPIRED_SIGNATURE_ERROR = 2 + STATUS_FIR + STATUS_SEC, '令牌过期！'
            TOKEN_DECODE_ERROR = 3 + STATUS_FIR + STATUS_SEC, '令牌解码失败！'
            TOKEN_INVALID_ERROR = 4 + STATUS_FIR + STATUS_SEC, '令牌非法！'
            TOKEN_UNKNOWN_ERROR = 5 + STATUS_FIR + STATUS_SEC, '令牌严重致命错误！'
            TOKEN_EFFECTIVE_BUT_UNKNOWN_RULE = 6 + STATUS_FIR + STATUS_SEC, '令牌合法，但无法理解令牌规则！'
            TOKEN_MISSING_NECESSARY_VALUE = 7 + STATUS_FIR + STATUS_SEC, '缺少制作令牌的必要值！'
            TOKEN_DESTROY = 8 + STATUS_FIR + STATUS_SEC, '令牌危险！合法但应该销毁！'


cs = CodeStatus().BasicCommunication().FaBBasicCommunication()
print(cs.ALL_VIEW_THEME_ASSETS_FAILURE)
