# Generated by Django 5.0.4 on 2024-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, unique=True)),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField()),
                ('expiration', models.BigIntegerField()),
                ('safe_level', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='WxUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
            ],
        ),
    ]
