# Generated by Django 5.0.3 on 2024-04-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, unique=True)),
                ('token', models.TextField()),
                ('expiration', models.BigIntegerField()),
                ('safe_level', models.IntegerField(default=5)),
            ],
        ),
    ]
