# Generated by Django 5.0.3 on 2024-04-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenLibrary',
        ),
    ]
