# Generated by Django 5.0.4 on 2024-05-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_users', '0002_delete_tokenlibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxusers',
            name='cart',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='wxusers',
            name='order',
            field=models.JSONField(default={'completed': {}, 'ongoing': {}, 'servicing': {}}),
        ),
        migrations.AlterField(
            model_name='wxusers',
            name='nickname',
            field=models.CharField(default='User_1714569894.8724864', max_length=255),
        ),
    ]
