# Generated by Django 5.0.4 on 2024-05-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_users', '0003_wxusers_cart_wxusers_order_alter_wxusers_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxusers',
            name='cart',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wxusers',
            name='nickname',
            field=models.CharField(default='User_1714570220.3331344', max_length=255),
        ),
    ]
