# Generated by Django 5.0.3 on 2024-05-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_users', '0004_alter_wxusers_cart_alter_wxusers_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxusers',
            name='nickname',
            field=models.CharField(default='User_1715052042.6610496', max_length=255),
        ),
        migrations.AlterField(
            model_name='wxusers',
            name='order',
            field=models.JSONField(default={'completed': {}, 'ongoing': {}, 'pending': {}, 'servicing': {}}),
        ),
    ]
