# Generated by Django 5.0.3 on 2024-04-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPageImages',
        ),
    ]
