# Generated by Django 5.0.3 on 2024-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='com_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='com_price',
            field=models.FloatField(),
        ),
    ]
