# Generated by Django 5.0.4 on 2024-04-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account', models.BigIntegerField()),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.TextField()),
            ],
        ),
    ]
